# Generated by Django 2.1.1 on 2018-12-20 18:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de inclusão da foto')),
                ('data_alteracao', models.DateField(auto_now=True, verbose_name='Data de inclusão da foto')),
                ('ativo', models.BooleanField(blank=True, default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Campus')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Informação Extra')),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campus',
                'ordering': ['-ativo', '-data_alteracao'],
            },
        ),
        migrations.CreateModel(
            name='CursoSetor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de inclusão da foto')),
                ('data_alteracao', models.DateField(auto_now=True, verbose_name='Data de inclusão da foto')),
                ('ativo', models.BooleanField(blank=True, default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Curso')),
                ('tipo', models.CharField(choices=[('Curso', 'Curso'), ('Setor', 'Setor')], max_length=25, verbose_name='Curso ou Setor?')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Campus')),
            ],
            options={
                'verbose_name': 'Curso / Setor',
                'verbose_name_plural': 'Cursos e Setores',
            },
        ),
        migrations.CreateModel(
            name='DescrisaoEspaco',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de inclusão da foto')),
                ('data_alteracao', models.DateField(auto_now=True, verbose_name='Data de inclusão da foto')),
                ('ativo', models.BooleanField(blank=True, default=True, verbose_name='Ativo?')),
                ('descricao', models.TextField(verbose_name='Informção sobre o espaço')),
                ('qtd_tomadas', models.PositiveIntegerField(verbose_name='Quantidade de tomadas')),
                ('qtd_computadores', models.PositiveIntegerField(verbose_name='Quantidade de computadores')),
            ],
            options={
                'verbose_name': 'Descrição da sala',
                'verbose_name_plural': 'Descrições das salas',
            },
        ),
        migrations.CreateModel(
            name='Espaco',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de inclusão da foto')),
                ('data_alteracao', models.DateField(auto_now=True, verbose_name='Data de inclusão da foto')),
                ('ativo', models.BooleanField(blank=True, default=True, verbose_name='Ativo?')),
                ('identificador', models.CharField(max_length=100, verbose_name='Indentificador do Espaço')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Informção extra')),
                ('qtd_bancadas', models.PositiveIntegerField(default=0, verbose_name='Quantidade de bancadas livres')),
                ('qtd_computadores', models.PositiveIntegerField(default=0, verbose_name='Quantidade de computadores')),
            ],
            options={
                'verbose_name': 'Espaço',
                'verbose_name_plural': 'Espaços',
                'ordering': ['-ativo', 'identificador'],
            },
        ),
        migrations.CreateModel(
            name='FotoEspaco',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de inclusão da foto')),
                ('data_alteracao', models.DateField(auto_now=True, verbose_name='Data de inclusão da foto')),
                ('ativo', models.BooleanField(blank=True, default=True, verbose_name='Ativo?')),
                ('foto', models.ImageField(upload_to='salas')),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Espaco')),
            ],
            options={
                'verbose_name': 'Foto do Espaço',
                'verbose_name_plural': 'Fotos do Espaço',
            },
        ),
        migrations.CreateModel(
            name='FotoPredio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de inclusão da foto')),
                ('data_alteracao', models.DateField(auto_now=True, verbose_name='Data de inclusão da foto')),
                ('ativo', models.BooleanField(blank=True, default=True, verbose_name='Ativo?')),
                ('foto', models.ImageField(null=True, upload_to='predios')),
            ],
            options={
                'verbose_name': 'Foto do Prédio',
                'verbose_name_plural': 'Fotos do Prédio',
            },
        ),
        migrations.CreateModel(
            name='Momento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de inclusão da foto')),
                ('data_alteracao', models.DateField(auto_now=True, verbose_name='Data de inclusão da foto')),
                ('ativo', models.BooleanField(blank=True, default=True, verbose_name='Ativo?')),
                ('identificador', models.CharField(max_length=100, verbose_name='Identificador')),
                ('inicio', models.DateField(verbose_name='Inicio do Momento')),
                ('termino', models.DateField(verbose_name='Fim do Momento')),
            ],
            options={
                'verbose_name': 'Momento',
                'verbose_name_plural': 'Momentos',
                'ordering': ['-ativo', '-data_alteracao'],
            },
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de inclusão da foto')),
                ('data_alteracao', models.DateField(auto_now=True, verbose_name='Data de inclusão da foto')),
                ('ativo', models.BooleanField(blank=True, default=True, verbose_name='Ativo?')),
                ('identificador', models.CharField(max_length=100, verbose_name='Indentificador do Predio')),
                ('descricao', models.TextField(verbose_name='Informção extra')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Campus')),
            ],
            options={
                'verbose_name': 'Prédio',
                'verbose_name_plural': 'Prédios',
                'ordering': ['-ativo', '-data_alteracao'],
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de inclusão da foto')),
                ('data_alteracao', models.DateField(auto_now=True, verbose_name='Data de inclusão da foto')),
                ('ativo', models.BooleanField(blank=True, default=True, verbose_name='Ativo?')),
                ('identificador', models.CharField(max_length=100, verbose_name='Número/Idenfificador da sala')),
                ('predio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.Predio')),
            ],
            options={
                'ordering': ['-ativo', 'identificador'],
            },
        ),
        migrations.AddField(
            model_name='fotopredio',
            name='predio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.Predio'),
        ),
        migrations.AddField(
            model_name='espaco',
            name='sala',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.Sala'),
        ),
    ]
