# Generated by Django 2.1.1 on 2018-12-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
        ('atividades', '0002_auto_20181220_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turmaatividade',
            name='qtd_encontro',
            field=models.PositiveIntegerField(blank=True, default=18, verbose_name='Quantidade de encontros'),
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('espaco', 'dia', 'turno')},
        ),
    ]
