"""
Django settings for sistemaEstagio project.

Generated by 'django-admin startproject' using Django 2.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

PRODUCAO = False

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'n^t0t2p*1!kishc+o0@98agr55_mcb&(cp0c-twhaf2*^1)#1n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# if PRODUCAO:
#     ALLOWED_HOSTS = ['sistemaestagio.pythonanywhere.com']
# else:

if PRODUCAO:
    ALLOWED_HOSTS = ['localhost','palmas.uft.edu.br']
else:
    ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'core',
    'contas',
    'academico',
    'atividades',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'labins.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'labins.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

if PRODUCAO:
    DATABASES = {
        'default': {
                'ENGINE': 'django.db.backends.mysql',
                'NAME': 'labins',
                'USER': 'labins',
                'PASSWORD': '***********',
                'HOST': 'mysql',
                'PORT': '3306',
                'OPTIONS': {
                # Tell MySQLdb to connect with 'utf8mb4' character set
                'charset': 'utf8mb4',
                }
            }
    }
else:
    ## RODANDO LOCAL COM BASE PRODUÇAO
    # DATABASES = {
    #     'default': {
    #             'ENGINE': 'django.db.backends.mysql',
    #             'NAME': 'labins',
    #             'USER': 'labins',
    #             'PASSWORD': 'BuyBt3sBoBfb',
    #             'HOST': 'palmas.uft.edu.br',
    #             'PORT': '32777',
    #             'OPTIONS': {
    #             # Tell MySQLdb to connect with 'utf8mb4' character set
    #             'charset': 'utf8mb4',
    #             }
    #         }
    # }

    ## RODANDO LOCAL COM BASE LOCAL
    DATABASES = {
        'default': {
                'ENGINE': 'mysql_cymysql',
                'NAME': 'labin',
                'USER': 'admin',
                'PASSWORD': 'admin',
                'HOST': 'localhost',
                'PORT': '',
                'OPTIONS': {
                   'init_command': 'SET sql_mode=\"STRICT_TRANS_TABLES\"',
                }
            }
    }


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'pt-BR'
TIME_ZONE = 'America/Araguaina'
USE_I18N = True
USE_L10N = True
USE_TZ = True
DATE_FORMAT = '%d/%m/%Y'
TIME_FORMAT = '%H:%M:%S'
DATE_INPUT_FORMATS = ('%d/%m/%Y',)


if PRODUCAO:
    STATIC_URL = '/labins/static/'

    STATIC_ROOT = os.path.join(BASE_DIR, 'static')
    STATICFILES_DIRS=(
        ('site', os.path.join(BASE_DIR, 'sitestatic')),

    )

    MEDIA_URL='/labins/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
else:

    STATIC_URL = '/static/'
    STATIC_ROOT = 'static'

    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
 
    MEDIA_URL = '/media/'

#AUTH_PROFILE_MODULE = 'painel.UserProfile'
#LOGIN_URL = '/painel/'



LOGIN_URL = 'login'
# LOGIN_REDIRECT_URL = 'contas:home'
LOGIN_REDIRECT_URL = 'contas:index'
LOGOUT_REDIRECT_URL = 'login'

AUTH_USER_MODEL = 'contas.Usuario'

URL_ADMINISTRA_TEMPLATE = ''

# AUTHENTICATION_BACKENDS = (
#     'django.contrib.auth.backends.ModelBackend',
#     'contas.backends.Mo delBackend',
# )
